anthy.el が使う廃止シンボル二つを直す
anthy-elisp を emacs30 で建てようとすると、.elc が二本できずに PLIST と
食い違って失敗する。

	ERROR: The following files are in the PLIST but not in .../usr/pkg:
	ERROR:         .../site-lisp/anthy/anthy-isearch.elc
	ERROR:         .../site-lisp/anthy/anthy-kyuri.elc

原因は anthy.el の 74 行目一行だった。

	(set-face-underline-p 'anthy-highlight-face t)

set-face-underline-p は Emacs 24.3 で set-face-underline の別名に降格し、
29 で削除された。この呼び出しはトップレベルにあるので、29 以降では
anthy.el を読むだけでエラーになる。anthy-isearch.el と anthy-kyuri.el は
(require 'anthy) しかしていないのに、そこで巻き添えになって byte-compile
できず、.elc が生まれない。emacs26 で建っていたのは、その版にまだ
set-face-underline-p が残っていたからにすぎない。

Emacs 20/21/23 には set-face-underline の側が無いので、改名ではなく
fboundp で分岐する。EMACS_VERSIONS_ACCEPTED に 20/21 を残す以上、
どちらの名前でも動く必要がある。

ついでに last-command-char も直した。こちらは Emacs 24 で消えている。
関数の中なので byte-compile は警告で済み、パッケージは建つ。ただし
japanese-anthy でキーを打った瞬間に落ちる。XEmacs 側の分岐は最初から
last-command-event を使っていて、GNU Emacs 側だけが取り残されていた。

patch は inputmethod/anthy/patches に置く。anthy-elisp が PATCHDIR と
DISTINFO_FILE を anthy と共有しているため。anthy 自身は .el を入れないので
そちらの PKGREVISION は据え置き、anthy-elisp を 7 に上げる。