emacs21: DragonFly で建つようにする
DragonFly では三つの壁がある。configure が machine を決められない、crt file
の path が 2007 年の compiler のまま、filelock.c が無い header を include
する。前の二つは netbsd-i386-8c が 2026-09-01 に切り分けたもので、当て物と
その註はそのまま引き取った。三つめはそこから先にあり、今回見つけて足した。

configure が x86_64 を知らない。pkgsrc の当て物が
`*-dragonfly* ) opsys=dragonfly' を足しているのに、machine を決める側に
x86_64 の汎用の枝が無く

	configure: error: Emacs hasn't been ported to `x86_64-pc-dragonfly'
	systems.

で止まる。editors/emacs20 は同じ枝を持っていて、こちらだけ残っていた。
netbsd と openbsd の case は同じ switch の手前にあるので、それらは変わらず
先に当たる。

crt file の path が gcc 4.4 と 4.1 の頃のまま。dragonfly.h が
/usr/lib/gcc44 と /usr/lib/gcc41 を名指していて、6.4 にはどちらも無い。
src を一つも compile しないうちに

	gmake[1]: *** No rule to make target '/usr/lib/gcc44/crtbegin.o'

で止まる。今の path を書き直しても次の compiler で同じことになるので、
s/netbsd.h と同じく ORDINARY_LINK にして cc に任せる。emacs20 と同じ手当て
だが、あちらが名指していたのは gcc41 の一箇所だけだった。

filelock.c が <utmp.h> を guard の外で include する。DragonFly は utmp を
utmpx へ移して header を落としたので

	filelock.c:68:10: fatal error: utmp.h: No such file or directory

で止まる。utmp の実体を使う所は全部 #ifdef BOOT_TIME の内側にあり、
BOOT_TIME は configure の結果ではなく glibc の <utmp.h> が定義する ut_type の
定数なので、header が無ければ未定義になって compile から消える。残るのは
include だけなので NO_UTMP_H で切る。emacs20 と同じ形の当て物で、違うのは
include の位置だけ。

REL_ALLOC の手当ては要らない。emacs21 の dragonfly.h は既に
USE_MMAP_FOR_BUFFERS を持っていて、そちらが上書きする。

建つことを確かめた。x11 が既定 options なので、同じ patches / files /
distinfo を使う emacs21-nox11 で測っている。x11 版は建てていない。

	DragonFly 6.4-RELEASE/x86_64、gcc 8.3、pkgsrc current の unprivileged
	bootstrap。devel/libuuid は CVS HEAD (Makefile.common 1.16) に差し替えた

	一回目 (utmp.h の手当て無し)   rc=1  filelock.c:68 で停止
	二回目 (NO_UTMP_H を足した)     rc=0  emacs21-nox11-21.4anb15.tgz (16MB)
	pkg_add                         rc=0
	emacs --version                 GNU Emacs 21.4.1
	system-configuration            x86_64-pc-dragonfly
	起動 10 回                       10/10
	(require 'cl)                   通る

BROKEN_ON_PLATFORM は Makefile.common で Darwin-*-* のみで、DragonFly は
元から除外されていない。建たなかったものが建つようになっただけなので、
そこは触っていない。PKGREVISION も動かさない。