mule-fedora: native X の検査が hostname を要求するのを満たす
Fedora 44 の最小コンテナには hostname が無く、pkgsrc の

  ERROR: /usr: X11_TYPE=native but xbase set is not installed
  (missing: hostname)

で can-be-built-here.mk が止めていた。1995 年の tree に届く前の段である。
hostname と、ついでに procps-ng と iproute を入れる。